openapi: 3.0.3
info:
  title: Harmadik házifeladat
  description: |-
    Node.js képzés harmadik házi feladat.
  version: 0.0.1
externalDocs:
  description: Online ide illeszthető be és jeleníthető meg.
  url: https://editor.swagger.io/
tags:
  - name: monkey
    description: Majommal kapcsolatos végpont
  - name: banana
    description: Banánnal kapcsolatos végpont
  - name: pairing
    description: Majom-banán párosítással kapcsolatos végpont
paths:
  /monkey:
    get:
      tags:
        - monkey
      summary: Az összes majom lekérdezése
      description: Az összes majom lekérdezése
      operationId: getAllMonkeys
      responses:
        '200':
          description: Az összes tárolt majom
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Monkey'
    post:
      tags:
        - monkey
      summary: Egy új majom hozzáadása
      description: Egy új majom hozzáadása
      operationId: addMonkey
      requestBody:
        description: |-
          Az új létrehozandó majom. 
          Nem tartalmazhat azonosítót.
          Nem lehet banánt egyből a majomhoz kötni.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Monkey'
        required: true
      responses:
        '201':
          description: Sikeres hozzáadás
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monkey'
        '400':
          description: |-
            Érvénytelen adatok a majomnak, 
            vagy tartalmaz azonosítót,
            vagy egyből banán hozzáadási kísérlet történt
  /monkey/{monkeyId}:
    get:
      tags:
        - monkey
      summary: Egy majom lekérdezése
      description: Egy majom lekérdezése (a hozzátartozó banánokkal együtt)
      operationId: getOneMonkey
      parameters:
        - name: monkeyId
          in: path
          description: Majom azonosítója
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sikeres lekérdezés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonkeyWithBanana'
        '400':
          description: Nem szám alapú azonosító
        '404':
          description: A majom nem található
    put:
      tags:
        - monkey
      summary: Egy majom frissítése
      description: |-
        Egy majom frissítése ID mentén.
        Nem lehet banán majomhoz kötésére használni.
      operationId: updateMonkey
      parameters:
        - name: monkeyId
          in: path
          description: Majom azonosítója
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Frissített majom adatok
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Monkey'
        required: true
      responses:
        '200':
          description: Sikeres frissítés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monkey'
        '400':
          description: |-
            Érvénytelen adatok a majomnak,
            vagy nem szám alapú azonosító,
            vagy banán hozzáadási kísérlet történt
        '404':
          description: A majom nem található
    delete:
      tags:
        - monkey
      summary: Egy majom törlése
      description: |-
        Egy majom törlése. 
        A hozzátartozó banánok felszabadításra kerülnek.
      operationId: deleteMonkey
      parameters:
        - name: monkeyId
          in: path
          description: Majom azonosítója
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sikeres törlés
        '400':
          description: Nem szám alapú azonosító
        '404':
          description: A majom nem található (nincs mit törölni)
  /banana:
    get:
      tags:
        - banana
      summary: Az összes banán lekérdezése
      description: Az összes banán
      operationId: getAllBananas
      responses:
        '200':
          description: Az összes tárolt banán
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Banana'
    post:
      tags:
        - banana
      summary: Egy új banán hozzáadása
      description: Egy új banán hozzáadása
      operationId: addBanana
      requestBody:
        description: |-
          Az új létrehozandó banán.
          Nem tartalmazhat azonosítót.
          Nem lehet egyből majomhoz kötni a banánt vele.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Banana'
        required: true
      responses:
        '201':
          description: Sikeres hozzáadás
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Banana'
        '400':
          description: |-
            Érvénytelen adatok a banánnak,
            vagy tartalmaz azonosítót,
            vagy majomhoz kötési kísérlet történt
  /banana/{bananaId}:
    get:
      tags:
        - banana
      summary: Egy banán lekérdezése
      description: Egy banán lekérdezése a tulajdonos majommal együtt
      operationId: getOneBanana
      parameters:
        - name: bananaId
          in: path
          description: Banán azonosítója
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sikeres lekérdezés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BananaWithMonkey'
        '400':
          description: Nem szám alapú azonosító
        '404':
          description: A banán nem található
    put:
      tags:
        - banana
      summary: Egy banán frissítése
      description: |-
        Egy banán frissítése ID mentén.
        Nem használható banán majomhoz kötésére.
      operationId: updateBanana
      parameters:
        - name: bananaId
          in: path
          description: Banán azonosítója
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Frissített banán adatok
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Banana'
        required: true
      responses:
        '200':
          description: Sikeres frissítés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Banana'
        '400':
          description: |-
            Érvénytelen adatok a banánnak,
            vagy nem szám alapú azonosító,
            vagy majomhoz kötési kísérlet történt
        '404':
          description: A banán nem található
    delete:
      tags:
        - banana
      summary: Egy banán törlése
      description: Egy banán törlése.
      operationId: deleteBanana
      parameters:
        - name: bananaId
          in: path
          description: Banán azonosítója
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sikeres törlés
        '400':
          description: Nem szám alapú azonosító
        '404':
          description: A banán nem található (nincs mit törölni)
  /pair/{bananaId}:
    delete:
      tags:
        - pairing
      summary: Egy banán felszabadítása
      description: |-
        Egy banán felszabadítása,
        azaz nem lesz egy majom tulajdonában sem ezután.
      operationId: freeBanana
      parameters:
        - name: bananaId
          in: path
          description: Banán azonosítója
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sikeres felszabadítás (vagy már szabad volt)
        '400':
          description: Nem szám alapú azonosító
        '404':
          description: A banán nem található
  /pair/{bananaId}/{monkeyId}:
    put:
      tags:
        - pairing
      summary: Banán majomhoz való kötése
      description: |-
        Egy banán ezzel köthető egy majomhoz.
        Nem kötelező előtte felszabadítani a banánt.
      operationId: bindBanana
      parameters:
        - name: bananaId
          in: path
          description: Banán azonosítója
          required: true
          schema:
            type: integer
            format: int64
        - name: monkeyId
          in: path
          description: Majom azonosítója
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sikeres hozzákötés
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BananaWithMonkey'
        '400':
          description: |-
            Nem szám alapú azonosító használata
            akár a majomnál, akár a banánnál
        '404':
          description: A banán vagy a majom nem található
components:
  schemas:
    Monkey:
      type: object
      description: Majom leírása
      required:
        - name
        - gender
        - species
      properties:
        id:
          type: integer
          description: Majom azonosítója
          format: int64
        name:
          type: string
          description: Majom neve
        gender:
          type: string
          description: Majom neme
        species:
          type: string
          description: Majom faja
        bananas:
          type: array
          description: A majom banánjainak azonosítói
          items:
            type: integer
            format: int64
    Banana:
      type: object
      description: Banán leírása
      required:
        - color
        - sweet
      properties:
        id:
          type: integer
          description: Banán azonosítója
          format: int64
        color:
          type: string
          description: Banán színe
          enum:
            - yellow
            - green
        sweet:
          type: boolean
          description: A banán édes-e vagy sem
        ownedByMonkey:
          type: integer
          description: A tulajdonos majom azonosítója
          format: int64
    MonkeyWithBanana:
      type: object
      description: Majom és a hozzá tartozó banánok
      required:
        - id
        - name
        - gender
        - species
      properties:
        id:
          type: integer
          description: Majom azonosítója
          format: int64
        name:
          type: string
          description: Majom neve
        gender:
          type: string
          description: Majom neme
        species:
          type: string
          description: Majom faja
        bananas:
          type: array
          items:
            $ref: "#/components/schemas/Banana"
    BananaWithMonkey:
      type: object
      description: Banán és az őt tulajdonló majom
      required:
        - id
        - color
        - sweet
      properties:
        id:
          type: integer
          description: Banán azonosítója
          format: int64
        color:
          type: string
          description: Banán színe
          enum:
            - yellow
            - green
        sweet:
          type: boolean
          description: A banán édes-e vagy sem
        ownedByMonkey:
          $ref: "#/components/schemas/Monkey"
